<?php

namespace TroisWA\BackBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
//    public function latestCat()
//    {
//        $query = $this->createQueryBuilder("prod")
//        ->orderBy('prod.date_created','desc')
//        ->getQuery();
//        return $query->getResult();
//
//
//    }


    public function CatQuantity()
    {


        $query = $this->createQueryBuilder("prod")
            ->select('count(prod.id)')
            ->getQuery();
        return $query->getSingleScalarResult();
    }



    public function catActive()
    {


        $query = $this->createQueryBuilder("prod")
            ->select('count(prod.id)')
            ->where('prod.activate = 1')
            ->getQuery();
        return $query->getSingleScalarResult();
    }

    public function catActInact()
    {

        $query = $this->createQueryBuilder("prod")
            ->select('count(prod.id)')
            ->groupBy('prod.activate')
            ->getQuery();
        return $query->getResult();
    }

    public function builderCategoryOrderPosition()
    {
        {
            return $this->createQueryBuilder("cat")
                ->orderBy("cat.position");
        }

    }

    public function catImage($id)
    {
        $query = $this->createQueryBuilder("cat")
            ->select('cat,img')
            ->join('cat.image', 'img')
            ->where('cat.id = :id')
            ->setParameter('id',$id)
            ->getQuery();
        return$query->getSingleResult();

    }

}
