<?php

namespace TroisWA\BackBundle\Repository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllGroups()
    {
        {
            return $this->createQueryBuilder("g");
        }

    }


}
