brand:
    path:     /{page}
    defaults: { _controller: "TroisWABackBundle:Brand:index", page: 1 }


brand_show:
    path:     /{id}/show
    defaults: { _controller: "TroisWABackBundle:Brand:show" }

brand_new:
    path:     /new
    defaults: { _controller: "TroisWABackBundle:Brand:new" }

brand_create:
    path:     /create
    defaults: { _controller: "TroisWABackBundle:Brand:create" }
    methods:  POST

brand_edit:
    path:     /{id}/edit
    defaults: { _controller: "TroisWABackBundle:Brand:edit" }

brand_update:
    path:     /{id}/update
    defaults: { _controller: "TroisWABackBundle:Brand:update" }
    methods:  [POST, PUT]

brand_delete:
    path:     /{id}/delete
    defaults: { _controller: "TroisWABackBundle:Brand:delete" }
    methods:  [POST, DELETE]
