
trois_wa_back_categories:
    path:     /
    defaults: { _controller: TroisWABackBundle:Category:index }

trois_wa_back_category:
    path:     /{id}
    defaults: { _controller: TroisWABackBundle:Category:cat }
    requirements:
              id: \d+
#             id: "[0-9]+"

trois_wa_back_category_add:
    path:     /add
    defaults: { _controller: TroisWABackBundle:Category:add }

trois_wa_back_category_edit:
    path:     /edit/{id}
    defaults: { _controller: TroisWABackBundle:Category:edit }

trois_wa_back_category_delete:
    path:     /delete/{id}
    defaults: { _controller: TroisWABackBundle:Category:delete }