
trois_wa_back_product_index:
    path:     /
    defaults: { _controller: TroisWABackBundle:Product:index }

trois_wa_back_product:
    path:     /{id}
    defaults: { _controller: TroisWABackBundle:Product:product }
    requirements:
                      id: \d+

trois_wa_back_product_custom:
    path:     /custom
    defaults: { _controller: TroisWABackBundle:Product:custom }

trois_wa_back_product_add:
    path:     /add
    defaults: { _controller: TroisWABackBundle:Product:add }

trois_wa_back_product_delete:
    path:     /delete/{id}
    defaults: { _controller: TroisWABackBundle:Product:delete }
    requirements:
                  id: \d+

trois_wa_back_product_edit:
    path:     /edit/{id}
    defaults: { _controller: TroisWABackBundle:Product:edit }
    requirements:
                      id: \d+


