
trois_wa_back_tags_index:
    path:     /
    defaults: { _controller: TroisWABackBundle:Tags:index }

trois_wa_back_tags:
    path:     /{id}
    defaults: { _controller: TroisWABackBundle:Tags:tag }
    requirements:
                      id: \d+

trois_wa_back_tags_custom:
    path:     /custom
    defaults: { _controller: TroisWABackBundle:Tags:custom }

trois_wa_back_tags_add:
    path:     /add
    defaults: { _controller: TroisWABackBundle:Tags:add }

trois_wa_back_tags_delete:
    path:     /delete/{id}
    defaults: { _controller: TroisWABackBundle:Tags:delete }
    requirements:
                  id: \d+

trois_wa_back_tags_edit:
    path:     /edit/{id}
    defaults: { _controller: TroisWABackBundle:Tags:edit }
    requirements:
                      id: \d+


