trois_wa_back_ressources_product:
    resource: "@TroisWABackBundle/Resources/config/Routing/product.yml"
    prefix: /product


trois_wa_back_ressources_main:
    resource: "@TroisWABackBundle/Resources/config/Routing/main.yml"


trois_wa_back_ressources_category:
    resource: "@TroisWABackBundle/Resources/config/Routing/category.yml"
    prefix: /category
