services:
#    trois_wa_back.example:
#        class: TroisWA\BackBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


#    trois_wa_back.util:
#        class: TroisWA\BackBundle\Util\Utility
#        arguments: [%competences%, @doctrine.orm.entity_manager, "ceci est du texte"]


    trois_wa_back.cart:
            class: TroisWA\BackBundle\Util\Cart
            arguments: [@doctrine.orm.entity_manager, @session]